### ISSUE TITLE
Have a ready-to-go state on the timer

### ISSUE THREAD

**Issue by jgrape** [crispab/countdowntimer#2]
The redy-to-go state shows an empty pie with the minutes:00

Enter this state when minutes are changed.
Enter this state when timer is reset using a reset |<< button

**Comment by oscarlantz** [comment]
I would also like an empty pie when pressing the refresh button in the browser.

**Comment by jgrape** [comment]
Done.

Reset button added.
Ready-to-go state is entered when reset is pressed, page is reloaded or the minutes are changed.
