### ISSUE TITLE
First time at countdowntimer.se I got this page

### ISSUE THREAD

**Issue by oscarlantz** [crispab/countdowntimer#4]
![img_4079](https://cloud.githubusercontent.com/assets/2387707/15929728/e304a752-2e4e-11e6-9380-53ba5f1b858f.PNG)

**Comment by jgrape** [comment]
For now use the sub-domain www.countdowntimer.se instead.

**Comment by jgrape** [comment]
Fixed DNS redirect now: countdowntimer.se --> www.countdowntimer.se
